apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
    - name: counter
      image: busybox
      args:
        [
          /bin/sh,
          -c,
          'i=0; while [ $i -lt ${LOOP} ]; do echo "{\"counter\":$i,\"date\":\"$(date)\"}"; i=$((i+1)); sleep ${SLEEP}; done',
        ]
      env:
      - name: LOOP
        value: "40"
      - name: SLEEP
        value: "0.2"
